
services:
  web:
    command: python manage.py runserver 0.0.0.0:8000   
    environment:
      - RUN_MIGRATIONS=true
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  nginx:
    # disable nginx in dev, or remove this service from override if you want
    # because Vue dev server will serve frontend directly
    # or optionally comment out ports to avoid conflict
    ports: []
